FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY package.json ./
COPY gateway/package.json ./gateway/package.json
COPY services/auth/package.json ./services/auth/package.json
COPY services/chat/package.json ./services/chat/package.json
COPY services/users/package.json ./services/users/package.json
COPY shared/package.json ./shared/package.json
RUN npm install

COPY services/chat/ ./services/chat/
COPY shared/ ./shared/

EXPOSE 3009

CMD ["npm", "run", "start:watch", "-w", "services/chat"]
