FROM node:20-alpine

WORKDIR /app

# curl para el healthcheck
RUN apk add --no-cache curl

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
COPY src ./src

EXPOSE 3003

CMD ["npm", "run", "start:watch"]
